Repository gojue/moling, pull requests merged in 2025-04, with the labels that each got.

#13 docs: add Japanese README file
  README.md
  README_JA_JP.md
  README_ZH_HANS.md
Labels: documentation, size:L, lgtm

#14 feat: implement log file rotation and enhance logging configuration
  cli/cmd/root.go
  services/browser.go
  services/browser_config.go
  services/browser_test.go
  services/file_system_config.go
  utils/rotewriter.go
Labels: enhancement, size:L

#16 Improve builder
  .github/workflows/release.yml
  Makefile
  README.md
  README_JA_JP.md
  README_ZH_HANS.md
  cli/cobrautl/help.go
Labels: enhancement, size:M

#17 feat: update CLI descriptions for clarity and accuracy
  cli/cmd/root.go
  client/client.go
Labels: documentation, size:XS

#20 fix: update README files to replace image links with direct URLs
  README.md
  README_JA_JP.md
  README_ZH_HANS.md
Labels: documentation, size:S

#22 feat: add MCP Client configuration to install script
  install/install.ps1
  services/file_system_windows.go
Labels: bug, enhancement, size:M

#24 feat: update dependencies and add Makefile for multi-platform builds
  Makefile.release
  go.mod
  go.sum
Labels: enhancement, size:M

#25 feat: add JavaScript debugging tools to browser automation
  services/browser.go
  services/browser_config.go
  services/browser_debugger.go
Labels: enhancement, size:L

#26 refactor: replace CallToolResult methods with NewToolResult methods for error handling
  services/browser.go
  services/browser_debugger.go
  services/command.go
  services/file_system.go
  services/service.go
Labels: enhancement, size:L

#27 feat: add client configuration paths for Trae and update README for mode naming
  README.md
  README_JA_JP.md
  README_ZH_HANS.md
  client/client_config_windows.go
  go.mod
  go.sum
Labels: documentation, enhancement, size:S

#28 support Cursor IDE (MCP Client)
  client/client_config.go
  client/client_config_windows.go
Labels: enhancement, size:XS

#29 Improves code consistency, adds PID management, and enhances user prompts.
  cli/cmd/config.go
  cli/cmd/perrun.go
  cli/cmd/root.go
  go.mod
  go.sum
  prompts/ filesystem.md
  prompts/browser.md
  prompts/command.md
  services/browser.go
  services/command.go
  services/config.go
  services/file_system.go
  services/moling.go
  services/moling_test.go
  services/register.go
  services/service.go
  services/utils.go
  utils/pid.go
  utils/pid_unix.go
  utils/pid_windows.go
  utils/utils.go
Labels: documentation, enhancement, size:XL

#33 fix: handle parent process exit to ensure MCP Server shutdown
  cli/cmd/root.go
Labels: bug, size:S

#35 feat: update command arguments and add new client configurations for Trae and Trae CN
  client/client.go
  client/client_config.go
  client/client_config_windows.go
Labels: enhancement, size:XS
